homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
serial:
  port: /dev/ttyUSB0
frontend:
  enabled: true
  port: 8099
devices:
  '0xa4c138fcb9a20c2b':
    friendly_name: Basement temp sensor
  '0x943469fffe83c386':
    friendly_name: Kitchen repeater
  '0x00124b002a62e4f6':
    friendly_name: Dad's plug repeater
  '0x84ba20fffed47916':
    friendly_name: Dad Room Sensor
  '0x90ab96fffe77317d':
    friendly_name: 'Family Room Sensor '
  '0xa4c13850849c6068':
    friendly_name: Garage Sensor
  '0x943469fffe832044':
    friendly_name: 'Chloe usb repeater '
  '0xa4c138151f375ba6':
    friendly_name: Media room sensor
  '0x70b3d52b6004f5cc':
    friendly_name: Media Room Plug
  '0xa4c138b414d8df05':
    friendly_name: 'Kitchen Leak Detector '
  '0xa4c138a211a9db90':
    friendly_name: Basement Leak Detector
  '0xa4c138febf85408f':
    friendly_name: Pantry Door Sensor
  '0xa4c138d960e443ab':
    friendly_name: Front Door Sensor
  '0x001788010d2f63ff':
    friendly_name: Dad Lamp Bulb
  '0xa4c1380a3d642565':
    friendly_name: 'Mud room door sensor '
  '0x00124b00292905b0':
    friendly_name: Dad Office Switch
  '0xa4c138ef6fd57ce8':
    friendly_name: Ping ping bulb (window)
  '0xa4c138c11ccd7ba5':
    friendly_name: 'Chloe room sensor '
  '0xa4c138c49e2d83da':
    friendly_name: 'Back door sensor '
  '0xa4c1386f605497c4':
    friendly_name: Mom room sensor
  '0xa4c1388c9b771daf':
    friendly_name: 'Living Room Remote '
  '0xa4c138ddc093bcad':
    friendly_name: 'Chloe Remote '
  '0x00124b00290fda6b':
    friendly_name: Board game switch
  '0x00124b00290fe822':
    friendly_name: Ping ping switch
advanced:
  log_level: debug
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  last_seen: ISO_8601
availability:
  enabled: true
  active:
    timeout: 10
  passive:
    timeout: 1500
version: 4
