mqtt:
  enabled: true
  host: 127.0.0.1
  port: 1883
  topic_prefix: frigate

motion:
  mask:
    - 435,304,154,309,0,421,0,305,0,0,425,0

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    front_door:
      - rtsp://compton:Sax0ph0n3!@192.168.1.56:554/h264Preview_01_main
      - ffmpeg:back#video=h264
    front_door_sub:
      - rtsp://compton:Sax0ph0n3!@192.168.1.56:554/h264Preview_01_sub
      - ffmpeg:back#video=h264

cameras:
  front_door:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/front_door_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    record:
      enabled: true
      events:
        retain:
          default: 3
          mode: motion

    detect:
      enabled: true
    snapshots:
      enabled: true
      retain:
        default: 10
    motion:
      mask:
        - 435,304,154,309,0,421,0,305,0,0,425,0
version: 0.14
